//! Codegen for the `commercial-config` feature: when enabled,
//! `ANA_COMPILED_CONFIG_PATH` must point at a `config.toml`-shaped file.
//! It is validated with `ana_config::parse_str` and baked into
//! `OUT_DIR`'s `compiled_config.rs` as a `'static` `CompiledConfig`
//! value, `include!`d by `src/config.rs`. This script does nothing when
//! the feature is off.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-env-changed=ANA_COMPILED_CONFIG_PATH");

    if env::var_os("CARGO_FEATURE_COMMERCIAL_CONFIG").is_none() {
        return;
    }

    let path = env::var("ANA_COMPILED_CONFIG_PATH").unwrap_or_else(|_| {
        panic!(
            "the `commercial-config` feature requires ANA_COMPILED_CONFIG_PATH \
             to point at a config.toml to bake in"
        )
    });
    println!("cargo:rerun-if-changed={path}");
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("could not read ANA_COMPILED_CONFIG_PATH={path}: {err}"));
    let config = ana_config::parse_str(&text)
        .unwrap_or_else(|err| panic!("invalid compiled config at {path}: {err}"));

    let rendered = render(&config);
    let out_dir = env::var("OUT_DIR").expect("cargo always sets OUT_DIR for build scripts");
    let dest = Path::new(&out_dir).join("compiled_config.rs");
    fs::write(&dest, rendered)
        .unwrap_or_else(|err| panic!("could not write {}: {err}", dest.display()));
}

fn render(config: &ana_config::AnaConfig) -> String {
    format!(
        "// @generated by build.rs -- do not edit.\n\
         pub(crate) struct CompiledConfig {{\n\
         \x20   pub default_channels: Option<&'static [&'static str]>,\n\
         \x20   pub allowed_channels: Option<&'static [&'static str]>,\n\
         \x20   pub dry_solve_channels: Option<&'static [&'static str]>,\n\
         \x20   pub pypi_to_conda_uri: Option<&'static str>,\n\
         }}\n\n\
         pub(crate) static COMPILED_CONFIG: CompiledConfig = CompiledConfig {{\n\
         \x20   default_channels: {},\n\
         \x20   allowed_channels: {},\n\
         \x20   dry_solve_channels: {},\n\
         \x20   pypi_to_conda_uri: {},\n\
         }};\n",
        render_slice(config.default_channels.as_deref()),
        render_slice(config.allowed_channels.as_deref()),
        render_slice(config.dry_solve_channels.as_deref()),
        render_opt_str(config.pypi_to_conda_uri.as_ref().map(url::Url::as_str)),
    )
}

fn render_slice(values: Option<&[String]>) -> String {
    match values {
        None => "None".to_string(),
        Some(values) => {
            let items: Vec<String> = values.iter().map(|v| format!("{v:?}")).collect();
            format!("Some(&[{}])", items.join(", "))
        }
    }
}

fn render_opt_str(value: Option<&str>) -> String {
    value.map_or_else(|| "None".to_string(), |v| format!("Some({v:?})"))
}
