[package]
name = "ana-requirements-txt"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "MIT"
description = "requirements.txt dependency parsing for ana"

[dependencies]
ana-dependency = { path = "../ana-dependency" }
rattler_conda_types = { workspace = true }
rayon = { workspace = true }
thiserror = { workspace = true }
uv-pep508 = { workspace = true }
